### ISSUE TITLE
Leading zeros in exchange number

### ISSUE THREAD

**Issue by raufaser** [mbridak/not1mm#103]
When sending an exchange serial number, e.g. 7, the app is sending 7. Common practice is to send leading zeroes until you reached 3 digit exchange number. In this example 007. 
It would be very nice to have this feature.

**Comment by mbridak** [comment]
Okay, that shouldn't be that hard.
Not being much of a contester myself I had no real opinion. During the last WPX I heard everything from none, one or two leading zeros. But implementing it might just be a one liner.

**Comment by mbridak** [comment]
@raufaser I've pushed a change which I believe resolves your issue.
