### ISSUE TITLE
Grid Locator Exchange Contest

### ISSUE THREAD

**Issue by hellmind** [mbridak/not1mm#109]
I would like to know if there is any contest where you only send and receive the grid, similar to the ARRL January VHF contest but without the number. If there isn't one, how can I go about adding it? I don't think it would be too complicated; I would just need to take a similar contest and modify it. Any guidance would be appreciated.

**Comment by mbridak** [comment]
The only one I'm aware of is the World Wide Digi DX Contest.
But I haven't gotten around to that one yet.
Mainly because I haven't gotten around to doing digital yet.
