### ISSUE TITLE
Setting VFO frequency by typing it to the callsign field

### ISSUE THREAD

**Issue by raufaser** [mbridak/not1mm#115]
**Is your feature request related to a problem? Please describe.**
It is not possible to manually set the VFO frequency by typing it to the callsign field and hit ENTER.

**Describe the solution you'd like**
Same way it is in N1MM. Type the kHz into the callsign field and hit ENTER.

**Additional context**
![Screenshot 2024-07-19 170256](https://github.com/user-attachments/assets/890ef2cc-6f79-4659-ba27-eb4b6f0fc7bb)

**Comment by mbridak** [comment]
Yes. It's not1mm. Type it in and press space.

**Comment by raufaser** [comment]
OMG. I will stand in the corner for the rest of the evening ;)
