### ISSUE TITLE
contest italian 40/80 ari 

### ISSUE THREAD

**Issue by ik3ocd** [mbridak/not1mm#124]
good morning, I'm Flavio ik3ocd, I would like to make a request if possible for your inclusion in the Italian 40/80 contest of the Italian radio amateurs association, thanks for your work to also allow Linux to operate in contests and better graphics. 73

**Comment by mbridak** [comment]
Hello Flavio, I can't find anything on this contest. Could you provide a link to a page with the rules/scoring etc?

**Comment by mbridak** [comment]
Ah, never mind, I found it. https://www.ari.it/contest-hf/contest-4080.html

Just so you know, this logger currently does not directly support RTTY.

But I'll put this on the TODO list.

**Comment by ik3ocd** [comment]
Hi Michael, thanks for your interest, yes I can give you this info in pdf
in Italian or directly from the ari site

keep in mind that this contest has various operating modes, see if it can
be arranged in your not1mm. bye and best regards ik3ocd flavio near venice


https://www.ari.it/contest-hf/contest-4080.html.




Il giorno mar 30 lug 2024 alle ore 17:15 Michael Bridak <
***@***.***> ha scritto:

**Comment by ik3ocd** [comment]
ah ok
Michael ti ringrazio molto per tuo disponibilità 🙌 i miei piu cordiali
saluti e a presto . 73 de ik3ocd flavio

Il giorno mar 30 lug 2024 alle ore 17:15 Michael Bridak <
***@***.***> ha scritto:

**Comment by mbridak** [comment]
added to todo
