### ISSUE TITLE
Clear older than ... minutes time not stored

### ISSUE THREAD

**Issue by dg9vh** [mbridak/not1mm#127]
**Describe the bug**
The "Clear older than xx minutes"-time is not stored in the configuration.

**To Reproduce**
1. Start Not1MM
2. Set timeout timer to 30 min(s)
3. connect to cluster
4. Stop Not1MM
5. Restart Not1MM
6. Timer is reset to 1 minute.

**Expected behavior**
The previous selected time should be stored and reloaded when starting.

**Comment by mbridak** [comment]
@dg9vh Hello. I just pushed a change that takes care of this issue.

Cheers! Mike K6GTE.
