### ISSUE TITLE
SAC Contest

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#138]
**Is your feature request related to a problem? Please describe.**
The SAC Contest is coming up this weekend:  https://www.sactest.net/blog/  Would love to try not1mm in this one but I'm totally happy if it will be added for the next year. I have to fix the keying anyway, see the discussion part in this repo. That may be a challenge enough for me.

**Comment by mbridak** [comment]
@awandahl I'll add it to the todo list.
