### ISSUE TITLE
Crash when fldigi is running

### ISSUE THREAD

**Issue by rolnas** [mbridak/not1mm#144]
When fldigi is running (probably because no QSO registered) not1mm (version 24.9.15) crashed:

Traceback (most recent call last):
  File "/home/XYZ/.local/pipx/venvs/not1mm/lib/python3.11/site-packages/not1mm/__main__.py", line 621, in fldigi_qso
    datadict[tag[0]] = tag[1].split(">")[1].strip()
                       ~~~^^^
IndexError: list index out of range
Aborted

When there no fldigi running not1mm runs without problems.

**Comment by rolnas** [comment]
Added one log entry to fldigi and not1mm don't crash anymore.

**Comment by mbridak** [comment]
Ah thanks. I'll fix it.
