### ISSUE TITLE
Program crash if callsign is not in QRZ

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#149]
**Describe the bug**
Using general logging, enter a callsign that is not in the QRZ database and the program crashes with the following output:

Traceback (most recent call last):
  File "/home/aw/.local/share/pipx/venvs/not1mm/lib/python3.12/site-packages/not1mm/__main__.py", line 2665, in watch_udp
    fname = json_data.get("result", {}).get("fname", "")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
Aborted

**To Reproduce**
1. Use general logging
2. Enter a callsign not existing in QRZ
3. Tab forward

**Expected behavior**
If callsign is not in QRZ do nothing

**Desktop (please complete the following information):**
 - Armbian Ubuntu 24.04

**Comment by mbridak** [comment]
@awandahl Thanks. Fixed.
