### ISSUE TITLE
Change port to 8000 when activating PyWinkeyer

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#166]
**Is your feature request related to a problem? Please describe.**
PyWinkeyer run on port 8000, not 6789 as cwdaemon does. This is not obvious.
**Describe the solution you'd like**
Port numbers change automatically depending of which keying you choose, as a convenience.
**Describe alternatives you've considered**
Clarifying help text.

**Comment by mbridak** [comment]
Even tho the port to use is listed in both projects documentation, I pushed a change addressing this issue.

I've made it so the placeholder text for the port numbers change based on which radio button is pressed.

![image](https://github.com/user-attachments/assets/71782b73-0cfd-4740-afa9-c933c37963b2)
![image](https://github.com/user-attachments/assets/4dae048d-391b-4db5-b927-d0b5187ba6c7)
![image](https://github.com/user-attachments/assets/cb2754dd-9c31-46b2-8e8e-464deaedfb71)

**Comment by awandahl** [comment]
Do people read documentation? ;) No! I did though...
