### ISSUE TITLE
Leading zero in CQWW CW CQ Zone

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#171]
**Describe the bug**
A leading zero is sent in the exchange of CQ Zone, in my case 014

**To Reproduce**
1. Run CQ WW CW
2. In this case I'm NOT using ESM feature
3. Exchange in F-key = {SNT} {SENTNR}
4. Same for RUN and S&P

**Expected behavior**
Without leading zero for exchange not being serial number, and even if serial number they could be removed, maybe by a setting...?

**Desktop (please complete the following information):**

**Additional context**

**Comment by mbridak** [comment]
@awandahl Hi. I think it would work correctly for you if you changed your exchange macro to `{SNT} {EXCH}`.

**Comment by awandahl** [comment]
Of course... thanks!
