### ISSUE TITLE
Portable stations have somtimes invalid[?] calls /P and same with /0...9 

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#174]
**Describe the bug**
Sometimes I can't work portable stations like DF4SR/P and same with other calls with slash /

**To Reproduce**
1. Enter a call /P and try to work that station
2. Can't work that one
3. Remove /P and it's fine to work
4. Add the /P again it doesn't work
5.  But not always....

**Expected behavior**
Possibility to work /P or /0...9 stations

**Comment by mbridak** [comment]
Hmm probably due to this line:

```python
elif (len(self.callsign.text()) > 2 and self.callsign.text().isalnum()):
```
which would return False if the string contains a '/' character.

Fix on the way.

**Comment by mbridak** [comment]
Pushed fix.
