### ISSUE TITLE
Show red text "Dupe" already when call is in callsign field

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#176]
**Is your feature request related to a problem? Please describe.**
The dupe is indicated *after* QSO has started and when reading/entering other station's exchange, which is too late.

**Describe the solution you'd like**
The red "Dupe" could be shown already when the call is in the callsign field. You then have to decide if you want to work the station (to get rid of hassle) or say QSO B4. It would also be extremely comfortable in S&P when using up/down arrows for navigating the bandmap, easier to see the dupes when the map is crowded.

**Describe alternatives you've considered**

**Additional context**

**Comment by mbridak** [comment]
Fixed w/ 24-10-17-1.

**Comment by awandahl** [comment]
Simply perfect!
