### ISSUE TITLE
Increase maximum CW speed to 50 wpm

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#177]
**Is your feature request related to a problem? Please describe.**
40 wpm is pretty standard for a big gun, some will definitely want to go higher.

**Comment by mbridak** [comment]
Pushed fix to source tree. It'll be in the next push to pypi.

**Comment by awandahl** [comment]
Thanks! As I'm working hundreds of fake QSOs when testing things out it's a time saver to run at 50 wpm..
