### ISSUE TITLE
Time for manually added calls to bandmap (Ctrl-M) is 01:00 and not actual time

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#181]
**Describe the bug**
Time for manually added calls to bandmap (Ctrl-M) is 01:00 and not actual time

**To Reproduce**
1. Add call to bandmap manually with Ctrl-M
2. Look at the time

**Expected behavior**
Correct time

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mbridak** [comment]
Merged PR#182.
It'll be published to pypi tomorrow.

**Comment by awandahl** [comment]
Thanks!
