### ISSUE TITLE
Changing the width of columns in QSO log window could be applied to both log headers

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#183]
**Is your feature request related to a problem? Please describe.**
When changing the width of columns (by dragging) it makes sense to apply this to both the log windows, upper and lower. I can't imagine a situation when I would like them to be different. If it's feasible. Just a bit of UX.

**Comment by mbridak** [comment]
Alright. Pushed change 24-10-20, So now if the top table header column is resized, the bottom table header column will also be resized to match. But not the other way around. Since this would cause neither to be resized.

**Comment by awandahl** [comment]
Very good! I guess you use the top table mostly anyway. This is very useful! Thanks!
