### ISSUE TITLE
Spots come as duplicates or multiplettes

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#189]
**Describe the bug**
Spots are coming as duplicates or multiplets, sometimes 5-6 times.

**To Reproduce**
Check spot/bandmap window

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: xubuntu 24.04
 - Version [24-10-22] 

**Additional context**

**Comment by mbridak** [comment]
Pushed fix with 24-10-22-1.
Thanks for the report.
