### ISSUE TITLE
flrig... I hate it. It hates me.

### ISSUE THREAD

**Issue by mbridak** [mbridak/not1mm#212]
I've apparently neglected flrig for too long.

Long enough that it's causing problems. I'm not able to get my QMX to switch from digi to CW. And noted fldigi locked up while using
if with not1mm as soon as I switch over to using flrig. Others noted the applications disappear when using flrig. So I'm probably dumping a bunch of garbage to flrig and confusing the other kids in the playground.

**Comment by mbridak** [comment]
@py4xx Okay pushed a change.
The flrig/fldigi/not1mm holy trinity works better here.
Update and give it a try please.

**Comment by py4xx** [comment]
> @py4xx Okay pushed a change. The flrig/fldigi/not1mm holy trinity works better here. Update and give it a try please.

Hi Michael... 73
I updated to version 24.11.10, but I still have the same problem of closing not1mm, and it won't open again until I close FLDigi.
TNX

**Comment by mbridak** [comment]
Open a terminal then type `not1mm` to launch it.
When it crashes or fails to open, it should print out why.

**Comment by mbridak** [comment]
Add check for valid ipv4 address.

**Comment by mbridak** [comment]
Are you still getting the crash? If so have you launched not1mm from a terminal so you can get the traceback output?

**Comment by mbridak** [comment]
stale
