### ISSUE TITLE
Kenwood TS-480HX stuck transmitting after voice message stops.

### ISSUE THREAD

**Issue by kelmercunha** [mbridak/not1mm#215]
Kenwood TS-480HX stuck transmitting after voice message stops.

**Comment by mbridak** [comment]
Hi, The only thing on my side is sending the command to rigctld/flrig to toggle the PTT on of off, which I've confirmed it does.
One thing I found while googling that may help if some distros have something called brltty installed which hijacks the serial device and causes all kinds of problems. You might want to check if you have something similar.
