### ISSUE TITLE
Remove "There are better general loggers like QLog, KLog, CQRLog" and implement ESM for general logging

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#221]
**Is your feature request related to a problem? Please describe.**
not1mm is what it is. No need to discourage the use of general logging. It's very good for DX style operating, but of course useless without ESM. I will use it at my 5X7W QTH for sure.

**Describe the solution you'd like**
Remove the mentioned text and implement ESM.

**Describe alternatives you've considered**
Using N1MM+ in Wine.

**Comment by mbridak** [comment]
Added ESM and Call history to General Logging. Give it a try. Wasn't sure how you wanted the flow to go. So made a guess.

**Comment by mbridak** [comment]
All contests now have ESM support.
