### ISSUE TITLE
Add support for realtime scoreboard

### ISSUE THREAD

**Issue by mbridak** [mbridak/not1mm#231]
Add support to post xml score info to contestonlinescore.com and hamscore.com.

Got the XML generating:

```xml
<?xml version="1.0"?>
<dynamicresults>
<contest>CQ-WW-CW</contest>
<call>K6GTE</call>
<class power="LOW" assisted = "ASSISTED" transmitter="ONE" ops="SINGLE-OP" bands="ALL" mode="CW" overlay="N/A"></class><club></club>
<soft>Not1MM</soft>
<version>24.11.27</version>
<qth>
  <cqzone>3</cqzone>
  <iaruzone>6</iaruzone>
  <arrlsection>ORG</arrlsection>
  <stprvoth>CA</stprvoth>
  <grid6>dm13at</grid6>
</qth>
<breakdown>
  <qso band="total" mode="ALL">5</qso>
  <mult band="total" mode="ALL" type="zone">5</mult>
  <mult band="total" mode="ALL" type="country">4</mult>
  <point band="total" mode="ALL">3</point>
</breakdown>
<score>27</score>
<timestamp>2024-12-01 06:22:25</timestamp>
</dynamicresults>
```

Just need to finish... Everything else.

**Comment by awandahl** [comment]
contest.run is another scoreboard used extensively in Europe. Good idea to add scoreboard features. Missed that last weekend.

**Comment by mbridak** [comment]
Yup, they even use the same xml tags.

**Comment by mbridak** [comment]
@awandahl Okay, tested realtime scoring with contest.run. Seems to work. Now I just have to add it to all the contest plugins...

![image](https://github.com/user-attachments/assets/6acff5b4-2199-447a-b99b-d0a0708b23c8)

**Comment by awandahl** [comment]
Great work! Thanks!

**Comment by mbridak** [comment]
complete
