### ISSUE TITLE
Tab key doesn't work when BandMap is activated

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#240]
**Describe the bug**
The tab key doesn't seem to work when BandMap is activated. 

**To Reproduce**
Try to tab from callsign to SNT field (to change the sent report) with and without BandMap activated. When BandMap is activated the focus switch to the "remove marked callsign" in the BandMap instead of tabbing between the fields.

**Expected behavior**
Tabbing between the entry fields

 - OS: xubuntu 24.04
 - Version 24.12.6

**Comment by mbridak** [comment]
Thanks for catching this. I always operate with the bandmap undocked from the main window and didn't notice that I didn't change the button focus policy when adding the button to the bandmap.

fixed now.
