### ISSUE TITLE
Display frequency unit in log window

### ISSUE THREAD

**Issue by qsantos** [mbridak/not1mm#34]
In the log window, it is unclear what unit should be used for the frequency:

![image](https://github.com/mbridak/not1mm/assets/8493765/396256a3-c28b-4dab-80d0-986e904008ad)

Changing the column header to `Freq (Hz)`, `Freq (kHz)` or `Freq (MHz)` would be enough to remove the ambiguity.

**Comment by mbridak** [comment]
Thanks I'll roll this into the related bug you posted.

**Comment by mbridak** [comment]
fixed with 23.9.3.1

**Comment by qsantos** [comment]
I confirm that this is fixed. Thanks!
