### ISSUE TITLE
Exporting only  one call?

### ISSUE THREAD

**Issue by DE8MSH** [mbridak/not1mm#46]
Hi.

I'm using v23.11.2. If I call "Generate ADIF" !1mm exports only one -- first? -- entry.

![Bildschirmfoto vom 2023-11-12 11-22-53](https://github.com/mbridak/not1mm/assets/2323972/be9ac03d-9501-4bb4-b23d-2ee483508a3a)

What am I doing wrong here?

**Comment by mbridak** [comment]
Most likely nothing. Can you start the program from a terminal, then export the adif and see if it pops out an error in the terminal?

**Comment by DE8MSH** [comment]
That:

`[19:38:51] DEBUG __main__ - generate_adif Line 2468: ******ADIF*****
Traceback (most recent call last):
  File "/home/superuser/.local/lib/python3.10/site-packages/not1mm/__main__.py", line 2469, in generate_adif
    self.contest.adif(self)
  File "/home/superuser/.local/lib/python3.10/site-packages/not1mm/plugins/general_logging.py", line 231, in adif
    if len(grid) > 1:
TypeError: object of type 'NoneType' has no len()
`

**Comment by mbridak** [comment]
Ah okay, thanks. I'll fix it.

**Comment by mbridak** [comment]
Okay, I've pushed an update. 
Hopefully this fixes the issue.

**Comment by DE8MSH** [comment]
Okay. 'll give it a try tomorrow morning. PC's off. 11:49 pm here .

**Comment by DE8MSH** [comment]
Seems to work now. Will test further.
