### ISSUE TITLE
Lookup not working?

### ISSUE THREAD

**Issue by DE8MSH** [mbridak/not1mm#48]
Hi.

If I enter the one or the other call: Lookup doesn't seems to be working.

![qth_1](https://github.com/mbridak/not1mm/assets/2323972/5d707e3c-5c38-4535-9a4d-07d012cbc671)

![qth_2](https://github.com/mbridak/not1mm/assets/2323972/24811444-577a-476f-8029-a344e079e3f4)

![qth_3](https://github.com/mbridak/not1mm/assets/2323972/62507608-c8fd-45ef-907f-e0044f9a5eb1)

It always shows same distances. But: OP 1 and OP 2 ware living in different areas.

What can I do to get real results?

Tnx dear OP.

**Comment by DE8MSH** [comment]
EDIT: Error msg seems to be:

> Exception in thread Thread-4 (check_callsign2):
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/user/.local/lib/python3.10/site-packages/not1mm/__main__.py", line 2239, in check_callsign2
>     theirgrid = response.get("grid")
> AttributeError: 'tuple' object has no attribute 'get'

**Comment by DE8MSH** [comment]
EDIT²: I enabled full log (directory debug) to have a look at it by myself first....

**Comment by DE8MSH** [comment]
Works. But does not work.

![image](https://github.com/mbridak/not1mm/assets/2323972/bf0dc29d-4168-4c39-ad97-cd6f15144fd7)

It gets data from HamQTH. But does not put data into fields...

**Comment by mbridak** [comment]
That helps a-lot thanks.

**Comment by mbridak** [comment]
I believe this is fixed.

**Comment by DE8MSH** [comment]
Hmm... I did source rebuild. Result:

https://github.com/DE8MSH/pasties/blob/main/!1mm_2

I cannot start not1mm again. I killed old directory, git cloned again. Same error.

commit up to b6bc812 worked for me yesterday.

**Comment by DE8MSH** [comment]
Okay. I had to 
rm -r ~/.local/lib/python3.10/site-packages/not1mm/
and
rm -r ~/.local/lib/python3.10/site-packages/not1mm-23.11.12.dist-info/
...

**Comment by DE8MSH** [comment]
Seems to work now. I have HamQTH only right now. So not all call will be lookuped. I'll subscribe QRZ.
