### ISSUE TITLE
timeout too low for cat interface (netrig)

### ISSUE THREAD

**Issue by rolnas** [mbridak/not1mm#74]
**Describe the bug**
Cannot use with quisk or other hamlib rigctld cat interfaces.

**Expected behavior**
Normal freq and mode readout.

**Additional context**
Problem in cat_interface.py line setting settimeout for rigctl socket. It was reduced to 0.1 in the lastest commit. Tested with original 0.5 and it is OK in my case.

**Comment by mbridak** [comment]
on it.
