### ISSUE TITLE
cannot open bandmap window

### ISSUE THREAD

**Issue by rolnas** [mbridak/not1mm#75]
**Describe the bug**
Cannot open bandmap window. In console output I see some traceback with Syntax error.
This traceback leads to line
 logger.debug(f"vfo value error {packet.get("vfoa")}")
which I changed to
 logger.debug(f"vfo value error {packet.get('vfoa')}")
and it started to work as expected.

**Comment by mbridak** [comment]
Thanks I'll fix it.
