### ISSUE TITLE
CWR should be logged as CW

### ISSUE THREAD

**Issue by tcarwash** [mbridak/not1mm#86]
**Summary**
QRZ and LOTW don't function correctly with log entries using CWR as mode instead of CW. 

**Description** 
Although functionally equivalent, QRZ doesn't consider CW == CWR and LOTW doesn't accept CWR as a valid mode at all. Rigctld reports CWR when some (e.g. IC7300) rigs are in CW-Reverse (upper sideband) mode, not1mm is logging this instead of just CW.

**Expected Behavior**
Some loggers handle this with a config setting like "report CWR as CW" It's probably just as fine to just change CWR into CW at some point before it's written to a file.

**Comment by mbridak** [comment]
I'll push a fix soon thanks!

**Comment by mbridak** [comment]
Okay, I pushed 24.3.15, hopefully fixing this.

**Comment by tcarwash** [comment]
Awesome, thanks and 73!
