### ISSUE TITLE
station setting defaults typo ;-)

### ISSUE THREAD

**Issue by ckuhtz** [mbridak/not1mm#97]
**Describe the bug**
Club: Americal Radio Relay League

**To Reproduce**
Install fresh, launch not1mm

**Expected behavior**
American Radio Relay League

**Screenshots**
![image](https://github.com/mbridak/not1mm/assets/6361444/4ccaef87-4de7-4c92-b89a-8be5fb1078ff)

**Desktop (please complete the following information):**
Ubuntu 23.10

**Additional context**
If not a bug, how do I join the Americal Radio Relay League? :)

**Comment by mbridak** [comment]
Well that should be easy to fix ;-)

**Comment by mbridak** [comment]
Fixed in source.
